### ISSUE TITLE
Many pages are not available

### ISSUE THREAD

**Issue by zhoukangcn** [byzer-org/byzer-doc#117]
```
404 - Not Found
```

List:

- https://docs.byzer.org/#/byzer-notebook/zh-cn/what's_new/new_features
- https://docs.byzer.org/#/byzer-notebook/zh-cn/operation/scheduler
- https://docs.byzer.org/#/byzer-notebook/zh-cn/use_case/case_1
- https://docs.byzer.org/#/byzer-notebook/zh-cn/appendix/faq

**Comment by ZhengshuaiPENG** [comment]
Thanks @zhoukangcn ， currently we are still writing the documentation， will close this once done
