### ISSUE TITLE
有太多令人费解的语法, 文档却只字未提

### ISSUE THREAD

**Issue by qsimu** [byzer-org/byzer-doc#224]
比如说下面这段示例的 st( ) 到底是在做什么事
`
load mockStream.`datasource` options 

stepSizeRange="0-3"

and valueFormat="csv"

and valueSchema="st(field(column1,string),field(column2,string),field(column3,string))"

as newkafkatable1;
`

这种非常多见

**Comment by Lindsaylin** [comment]
> 

很真实的反馈，我们也意识到了这个问题。3-4月会集中优化一波手册，会细致每一章的内容和文案，解决大家的困惑。

**Comment by qsimu** [comment]
公司是让程序员搭建mlsql运行环境, 实际使用的人是数据分析师, 他们对于语法表示非常难学, 而且网上找不到教程.

**Comment by Lindsaylin** [comment]
> 嗯嗯，其实Byzer(原MLSQL）是类SQL 语句，上手肯定是不难的，但是手册和教程的确现在还不完善，在补充当中。
你加我一下微信吧：373260061
我们可以让团队小伙伴给你们做一下 One On One 的分享和教学，你们团队有什么问题也可以整理一下我们一起解答。
